#!/usr/bin/env node

import { promises as fs } from "fs";
import path from "path";

import chalk from "chalk";
import fse from "fs-extra";
import ora from "ora";
import YAML from "yaml";

import { LambdaClient } from "@aws-sdk/client-lambda";
import { fromIni } from "@aws-sdk/credential-providers";

import { createDeploymentPackage } from "../helpers/createDeploymentPackage";
import { deployFunction } from "../helpers/deployFunction";
import { showStatusOnly } from "../helpers/showStatusOnly";
import { validateDeployOptions } from "../helpers/validateDeployOptions";
import { DeployOptions, LambdaFunctionConfig, ParsedSAMTemplate, SAMTemplate } from "../types/app";
import { validateTemplate, formatValidationErrors } from "../helpers/validateTemplate";

const DEFAULT_ROLE_ARN = "arn:aws:iam::358922846691:role/service-role/prescription-generator-role-c9fkws8j";

const parseTemplate = async (templatePath: string): Promise<ParsedSAMTemplate> => {
  const templateContent = await fs.readFile(templatePath, "utf-8");
  const template: SAMTemplate = YAML.parse(templateContent);

  // Validate template structure before processing
  const validationErrors = validateTemplate(template);
  if (validationErrors.length > 0) {
    throw new Error(formatValidationErrors(validationErrors));
  }

  const resources = template.Resources || {};

  const lambdaResource = Object.entries(resources).find(([, resource]) => resource.Type === "AWS::Serverless::Function");

  if (!lambdaResource) {
    throw new Error("No AWS::Serverless::Function resource found in template.yaml");
  }

  const [resourceName, resource] = lambdaResource;
  const properties = resource.Properties!; // Safe to use ! after validation

  return {
    functionName: resourceName,
    runtime: properties.Runtime!,
    handler: properties.Handler!,
    timeout: properties.Timeout!,
    memorySize: properties.MemorySize!,
    codeUri: properties.CodeUri!,
  };
};

async function createLambdaClient(options: DeployOptions): Promise<LambdaClient> {
  // Await the fromIni promise only if needed
  const creds = options.profile !== "default" ? await fromIni({ profile: options.profile }) : undefined;

  const lambdaClient = new LambdaClient({
    region: options.region,
    credentials: creds,
  });

  return lambdaClient;
}

async function deployLambda(options: DeployOptions) {
  // Validate deploy options first
  const spinner = ora("Preparing deployment...\n").start();

  spinner.text = "Validating deployment options...";
  await validateDeployOptions(options);

  try {
    const templatePath = path.join(process.cwd(), "template.yaml");
    if (!(await fse.pathExists(templatePath))) {
      throw new Error(
        "template.yaml not found in current directory. Make sure you are in a Lambda project directory generated by lal-lambda-tools.",
      );
    }

    spinner.text = "Parsing and validating template.yaml...";

    const templateConfig = await parseTemplate(templatePath);

    const functionName = options.functionName || templateConfig.functionName;

    spinner.text = "Setting up AWS clients...";

    const lambdaClient = await createLambdaClient({
      profile: options.profile,
      region: options.region,
    });

    if (options.statusOnly) {
      showStatusOnly(spinner, lambdaClient, functionName);
      return;
    }

    spinner.text = "Using execution role...";
    const roleArn = options.role || DEFAULT_ROLE_ARN;

    spinner.text = "Creating deployment package...";
    const zipBuffer = await createDeploymentPackage(templateConfig.codeUri);

    spinner.text = `Deploying Lambda function: ${functionName}...`;

    const functionArn: string = await deployFunction(lambdaClient, <LambdaFunctionConfig>{
      functionName: functionName,
      runtime: templateConfig.runtime,
      handler: templateConfig.handler,
      timeout: templateConfig.timeout,
      memorySize: templateConfig.memorySize,
      roleArn: roleArn,
      zipBuffer: zipBuffer,
    });

    spinner.succeed(chalk.green("✅ Lambda function deployed successfully!"));
    console.log(chalk.blue("🚀 Function Name: " + functionName));
    console.log(chalk.blue("📍 Region: " + options.region));
    console.log(chalk.blue("🔗 Function ARN: " + functionArn));
    console.log(chalk.blue("⚡ Runtime: " + templateConfig.runtime));
    console.log(chalk.blue("🎯 Handler: " + templateConfig.handler));
  } catch (error) {
    spinner.fail(`❌ Deployment failed: ${error}`);
    throw error;
  }
}

export { deployLambda };
